function sim_struct = init_sim_struct(varargin)

keys = {'tspan', 'sim_mode', 'pulse_mode', 'save_data_flag', 'parallel_flag',...
    'include_IB', 'include_NG', 'include_RS', 'include_FS', 'include_LTS',...
    'include_deepFS', 'include_deepRS'};

values = {[0 1000], 1, 0, 0, 1,...
    0, 0, 0, 0, 0,...
    0, 0};

sim_struct = init_struct(keys, values, varargin{:});