function run_distractor_simulations

model_data_name = {'19-01-24/kramer_IB_17_6_31.38', '19-01-30/kramer_IB_11_20_58.05',...
    '19-02-07/kramer_IB_14_54_48.77', '19-01-30/kramer_IB_17_6_54.67',...
    '19-02-27/kramer_IB_15_27_0.6538'};

model_names = {'M', 'I', 'IC', 'MC', 'MIC'};

cd /projectnb/crc-nak/brpp/model-dnsim-kramer_IB/kramer_IB/Figs_Ben; model_vary = get_model_vary; cd ..;

include_deepFS = [0 1 1 1 0];

simulation_vary = {'deepRS', 'mechanism_list', '+iPeriodicDistractors';...
    'deepRS', 'PDfreq', 1:.5:13;...
    'deepRS', '(PPstim, PDstim)', [0 -.01:-.01:-.1];... '(PPstim, PDstim)', [0 -1:-.5:-4];... % 'deepRS', 'PDstim', -2;... % 'PPstim', 0:-.5:-4;... % 
    'deepRS', 'PPfreq', 7;...
    'deepRS', 'PPduty', .25;...
    'deepRS', 'kernel_type', 25;...
    'deepRS', 'PPjitter', .025;...
    'deepRS', 'PDduty', .25;...
    'deepRS', 'PDkernel_type', 25;...
    'deepRS', 'PDjitter', .025;...
    % 'deepRS', 'PDshift', .5;...
    };

data_name = cell(length(model_names), 1);

data_date = datestr(datenum(date),'yy-mm-dd');

Now = clock;

for m = 1:length(model_vary)
    
    vary = [model_vary{m}; simulation_vary]
    
    sim_struct = init_sim_struct('vary', vary, 'include_deepRS', 1,...
        'include_deepFS', include_deepFS(m), 'tspan', [0 30000],...
        'cluster_flag', 1, 'parallel_flag', 0, 'save_data_flag', 1, 'sim_mode', 3,...
        'note', ['Distractor simulations for model ', model_names{m}],...
        'parent', model_data_name{m});
    
    [~, data_name{m}] = kramer_IB_function_mode(sim_struct);

end

sim_name = sprintf('distractor_%s_%d', data_date, Now(4));

save([sim_name, '.mat'], 'sim_name', 'data_name')