#!/bin/sh -l

#$ -pe omp 16

echo "Executing run_timit_simulations"

module load matlab/2018a

matlab -nosplash -nodisplay -r "kIB_Figs_dir, run_timit_simulations, exit"

# for i in Figs_Ben/18-02-16/*sim_spec.mat;
# do j=$(basename $i);
# echo run_make_fig2_function 18-02-16 ${j%'_sim'*} 1 1 1;
# done