#!/bin/sh -l
# First argument is date folder; second is name of simulation.

#$ -t 1-3

thresholds=(.667 .5 .333)
# syncwins=(100 75 50 25)
index=$(($SGE_TASK_ID-1))
threshold=${thresholds[$index]}
# syncwin=${syncwins[$index]}

for j in 75 50 25;
do
echo "Executing cd '$1', getSumThresh(sim_name, [$j; "$threshold"]), exit";
matlab -nosplash -nodisplay -r "Figs_Ben_dir, cd '$1', getSumThresh('$2', [$j; "$threshold"]), exit";
done