#!/bin/sh -l

#$ -pe omp 16

echo "Executing cd '"$1"', load(['"$2"', '_sim_spec.mat']),\
 data = dsImport(name);  spike_locking_to_input_plot(data, [], name,\
 'i_field', 'deepRS_iFMPulses_input', 'f_field', 'deepRS_FMPlowfreq', 'i_transform', 'hilbert')"

#module unload matlab/2014a

module load matlab/2018a

matlab -nosplash -nodisplay -r "Figs_Ben_dir, cd '$1', load(['$2', '_sim_spec.mat']),\
 data = dsImportDataOrResults(name); spike_locking_to_input_plot(data, [], name,\
 'i_field', 'deepRS_iFMPulses_input', 'f_field', 'deepRS_FMPlowfreq', 'i_transform', 'hilbert');\
 spike_locking_to_input_plot(data, [], name, 'i_field', 'deepRS_iFMDistractors_input',\
 'f_field', 'deepRS_FMDlowfreq', 'i_transform', 'hilbert'); exit"

# for i in Figs_Ben/18-02-16/*sim_spec.mat;
# do j=$(basename $i);
# echo run_make_fig2_function 18-02-16 ${j%'_sim'*} 1 1 1;
# done