#!/bin/sh -l

#$ -pe omp 16

# #$ -l h_rt=24:00:00

echo "Executing cd '"$1"', load(['"$2"', '_sim_spec.mat']), data = dsImport(name);\
    spike_locking_to_input_plot(data, [], name, 'i_field', 'deepRS_iSpeechInput_input',\
    'i_transform', 'wavelet_reduce', 'no_periods', -2, 'p_field', 'deepRS_iSpeechInput_syllables'))"

#module unload matlab/2014a

module load matlab/2018a

matlab -nosplash -nodisplay -r "Figs_Ben_dir, cd '$1', load(['$2', '_sim_spec.mat']),\
    data = dsImportDataOrResults(name); plots_by_variable('deepRS_SentenceIndex', @plot_2_vars,\
    data, '$2', {'deepRS_V', 'deepRS_iSpeechInput_input'}, [], [1 4]*10^4, [6, 8]), exit"

# for i in Figs_Ben/18-02-16/*sim_spec.mat;
# do j=$(basename $i);
# echo run_make_fig2_function 18-02-16 ${j%'_sim'*} 1 1 1;
# done

#spike_locking_to_input_plot(data, [], name,\