#!/bin/sh -l

#$ -pe omp 16

echo "Executing cd '"$1"', results = dsImportResults('"$2"', @boundary_analysis); plotBoundaryAlternation("'$2'", results, results), exit"

#module unload matlab/2014a

module load matlab/2018a

matlab -nosplash -nodisplay -r "kIB_Figs_dir, cd '$1', results = dsImportResults('$2', @boundary_analysis); plotBoundaryAlternation('$2', results, results), exit"

# for i in Figs_Ben/18-02-16/*sim_spec.mat;
# do j=$(basename $i);
# echo run_make_fig2_function 18-02-16 ${j%'_sim'*} 1 1 1;
# done
