function run_distractor_simulations_v1

data_name = {'19-01-24/kramer_IB_17_6_31.38', '19-01-30/kramer_IB_11_20_58.05',...
    '19-02-07/kramer_IB_14_54_48.77', '19-01-30/kramer_IB_17_6_54.67',...
    '19-02-27/kramer_IB_15_27_0.6538'};

model_names = {'M', 'I', 'IC', 'MC', 'MIC'};

cd /projectnb/crc-nak/brpp/model-dnsim-kramer_IB/kramer_IB/Figs_Ben; model_vary = get_model_vary; cd ..;

include_deepFS = [0 1 1 1 0];

simulation_vary = {'deepRS', 'mechanism_list', '+iFMPulses';...
    'deepRS', 'mechanism_list', '+iFMDistractors';...
    'deepRS', 'FMPlowfreq', 6.5;...
    'deepRS', 'FMPhighfreq', 7.5;...
    'deepRS', '(FMDlowfreq, FMDhighfreq)', [1.5:.5:11.5; 2.5:.5:12.5];
    'deepRS', '(FMPstim, FMDstim)', [0 -.75:-.25:-2.5];...
    'deepRS', 'PPstim', 0;...
    };

for m = 1:length(model_vary)
    
    vary = [model_vary{m}; simulation_vary]
    
    sim_struct = init_sim_struct('vary', vary, 'include_deepRS', 1,...
        'include_deepFS', include_deepFS(m), 'tspan', [0 30000],...
        'cluster_flag', 1, 'parallel_flag', 0, 'save_data_flag', 1, 'sim_mode', 3,...
        'note', ['Distractor simulations for model ', model_names{m}],...
        'parent', data_name{m});
    
    [~,~] = kramer_IB_function_mode(sim_struct);

end