vary = {'deepRS', 'I_app', -9.2;...
    'deepRS', 'mechanism_list', '+iSpikeTriggeredPulse';...
    'deepRS', 'STPshift', 0;...
    'deepRS', 'STPstim', 0:-50:-1000;... % [0 -10];...
    'deepRS', 'STPkernelType', 25;... % 7;... %
    'deepRS', 'STPonset', 1000;...
    'deepRS', 'STPwidth', 50;...
    'deepRS', 'PPstim', 0;...
    'deepRS', 'FMPstim', 0;...
    'deepRS', 'Inoise', 0.25;
    };

sim_struct = init_sim_struct('vary', vary, 'include_deepRS', 1, 'tspan', [0 2000],...
    'cluster_flag', 1, 'save_data_flag', 1, 'sim_mode', 8,...
    'note', 'Spike-triggered input pulse for ST inhibitory buildup plot.',...
    'parent', '19-01-07/kramer_IB_21_18_58.89');

[~, ~] = kramer_IB_function_mode(sim_struct);