




function run_setdefaultfig

% set(0, 'DefaultFigureColor', 'White', ...
% 'DefaultFigurePaperType', 'a4letter', ...
% 'DefaultAxesColor', 'white', ...
% 'DefaultAxesDrawmode', 'fast', ...
% 'DefaultAxesFontUnits', 'points', ...
% 'DefaultAxesFontSize', 14, ...
% 'DefaultAxesFontAngle', 'Italic', ...
% 'DefaultAxesFontName', 'Times', ...
% 'DefaultAxesGridLineStyle', ':', ...
% 'DefaultAxesInterruptible', 'on', ...
% 'DefaultAxesLayer', 'Bottom', ...
% 'DefaultAxesNextPlot', 'replace', ...
% 'DefaultAxesUnits', 'normalized', ...
% 'DefaultAxesXcolor', [0, 0, 0], ...
% 'DefaultAxesYcolor', [0, 0, 0], ...
% 'DefaultAxesZcolor', [0, 0, 0], ...
% 'DefaultAxesVisible', 'on', ...
% 'DefaultLineColor', 'Red', ...
% 'DefaultLineLineStyle', '-', ...
% 'DefaultLineLineWidth', 2, ...
% 'DefaultLineMarker', 'none', ...
% 'DefaultLineMarkerSize', 8, ...
% 'DefaultTextColor', [0, 0, 0], ...
% 'DefaultTextFontUnits', 'Points', ...
% 'DefaultTextFontSize', 14, ...
% 'DefaultTextFontName', 'Times', ...
% 'DefaultTextVerticalAlignment', 'middle', ...
% 'DefaultTextHorizontalAlignment', 'left');

format compact
matlab_default=10;
enlarged=14;

scaling_factor=get_scaling_factor;

set(0, 'DefaultFigureColor', 'White', ...
    'DefaultTextFontSize', get_fontlevel(4)*scaling_factor, ...
    'DefaultAxesFontSize', get_fontlevel(2)*scaling_factor);

% set(0,'DefaultFigurePosition',[ 530   336   479   349])%Default
% set(0,'DefaultFigurePosition',[ 332         474        1062         400]) % Wide
% set(0,'DefaultFigurePosition',[530   111   674   574]) % Slightly enlarged, square
% set(0,'DefaultFigurePosition',[282   206 674*scaling_factor   574*scaling_factor]) % Slightly enlarged, square
set(0,'DefaultFigurePosition',[282   206 724*scaling_factor   477*scaling_factor]) % Slightly enlarged, rectangular
%set(0,'DefaultFigurePosition',[ 258   215   510*scaling_factor/1.5   287*scaling_factor/1.5]) % Slightly enlarged, rectangular


end