
%% Open default set of scripts for editing
edit kramer_IB/kramer_IB_deltapaper_tune1
edit kramer_IB/kramer_IB_deltapaper_scripts2
edit kramer_IB/kramer_IB_clustersub
edit kramer_IB/kramer_IB
edit kramer_IB/include_kramer_IB_populations
edit kramer_IB/include_kramer_IB_synapses
edit kramer_IB/include_kramer_IB_simulate
edit kramer_IB/include_kramer_IB_plotting
edit save_allfigs_Dave
